name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  auto-pull:
    name: Pull Origin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ssh clone git@github.com:NCScorp/teste-githubaction.git
        git pull origin main
      working-directory: /home/elnico/Documents/vscode/projeto/
