name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: autopull
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          script: ./autopull.sh
